---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nmstate-operator
  namespace: openshift-nmstate
subjects:
- kind: ServiceAccount
  name: nmstate-operator
  namespace: openshift-nmstate
roleRef:
  kind: Role
  name: nmstate-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nmstate-operator
  namespace: openshift-nmstate
subjects:
- kind: ServiceAccount
  name: nmstate-operator
  namespace: openshift-nmstate
roleRef:
  kind: ClusterRole
  name: nmstate-operator
  apiGroup: rbac.authorization.k8s.io
