apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-operator-controller-manager
  namespace: metallb-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: DEPLOY_SERVICEMONITORS
          value: "true"
        - name: METALLB_BGP_TYPE
          value: "frr"
        - name: FRR_IMAGE
          value: quay.io/frrouting/frr:8.4.2

